name = "2 Old 4 Pack"
author = "MDidia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93674dcbcad761d6017e31a6e9d7969661907cd48f7c113f4f0529071fa2d876"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.18"
