name = "2 Old 4 Pack"
author = "MDidia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "286398a420d2dcdb01387b9bca8f2a199e1527e48520c4c8f8d15563e76f7d58"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.18"
